### ISSUE TITLE
RuntimeError: The layer has never been called and thus has no defined output shape

### ISSUE THREAD

**Issue by germal** [diggerdata/kolt_ros#2]
Hello @diggerdata ,

I installed Kolt with tensorflow 2.3.0 on a Nvidia Jetson Nano ( with 4 Gb ram ) using a D435 as  camera.
I tried full_yolo and tiny_yolo, setting it in yolo_server.launch 
Launching the k_rs_camera.launch I get the following errors 

`
2020-11-08 16:35:44.450292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 295 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
Traceback (most recent call last):
  File "/home/mluser/kolt_ws/src/kolt_ros/scripts/yolo_server.py", line 114, in <module>
    ys = YoloServer()
  File "/home/mluser/kolt_ws/src/kolt_ros/scripts/yolo_server.py", line 45, in __init__
    anchors = self.anchors
  File "/home/mluser/kolt_ws/src/kolt_ros/src/core/frontend.py", line 96, in __init__
    rospy.logdebug(self.feature_extractor.get_output_shape())    
  File "/home/mluser/kolt_ws/src/kolt_ros/src/core/backend.py", line 30, in get_output_shape
    return self.feature_extractor.get_output_shape_at(-1)[1:3]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 2030, in get_output_shape_at
    'output shape')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 2603, in _get_node_attribute_at_index
    'and thus has no defined ' + attr_name + '.') 
RuntimeError: The layer has never been called and thus has no defined output shape. `

I tried  to limit the Tensorflow memory with a legacy block inside frontend.py (with memory_fraction = 0.x)

`
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
config = ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.8
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config) `

or with corresponding 2.x code instructions as well, creating a virtual GPU with 1024 up to 2048 Mb , but the result is the same

`gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
    tf.config.experimental.set_virtual_device_configuration(
        gpus[0],
        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e) `

Could you please advice on how to resolve the issue and the versions of Keras and tensorflow that you used , in order to match as much as possible your configuration ?
Thanks for all ,
Regards
germal

**Comment by germal** [comment]
I downgraded the Tensorflow version to 2.0
